name: strapi-test
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Проверка кода из репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'v22.2.0'

      - name: Сетап проекта
        run: make setup

      - name: Запуск тестов
        run: make test

      - name: Запуск линтера
        run: make lint
      - name: Hello from Hexlet!
        uses: hexlet-components/hello-from-hexlet-action@release
  