name: strapi-test
on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Проверка кода из репозитория
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: Use Node.js ${{ matrix.node-version }}
          cache: npm

      - name: Сетап проекта
        run: make setup

      - name: Запуск тестов
        run: make test

      - name: Запуск линтера
        run: make lint
        
      - name: Hello from Hexlet!
        uses: hexlet-components/hello-from-hexlet-action@release
  